---
title: "Wine Data API Vignette"
author: "Annie Brinza"
date: '2022-10-07'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This document is a vignette about contacting an API using functions we've created to
query, parse, and return well-structured data. We’ll then use our functions to obtain data from the API
and do some exploratory data analysis. Kara Belknap and Annie Brinza worked on this project. We decided to use wine data from the food data API. Specifically, we will be focusing on general wine recommendations, dish pairings to go with a certain wine, and wine recommendations given a certain dish. We will be building functions to accomplish all of that.

To interact with these functions, either a general wine type such as "merlot" needs to be given, or a dish or cuisine type such as "Italian." This will be detailed further for each of the API calls.

## Requirements
WILL FILL OUT LATER


## API Interaction Functions
In this section, we will define functions to interact with the various wine APIs found [here](https://spoonacular.com/food-api/docs#Wine-Guide). We will be pulling from three different APIs: [Wine Recommendation](https://spoonacular.com/food-api/docs#Wine-Recommendation), [Wine Pairing](https://spoonacular.com/food-api/docs#Wine-Pairing), and [Dish Pairing for Wine](https://spoonacular.com/food-api/docs#Dish-Pairing-for-Wine). 

The APIs do not require an authentication key to access, so it is fairly simple to be able to access them. 

### Wine Recommendation Function

### Wine Pairing Function

### Dish Pairing for Wine
